//Auth action
export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_INCORRECT_LOGIN_DETAILS = 'AUTH_INCORRECT_LOGIN_DETAILS';

//GENERIC FETCH ACTIONS

export const FETCH_START = 'FETCH_START';
export const FETCH_SUCCESS = 'FETCH_SUCCESS';
export const FETCH_FAIL = 'FETCH_FAIL';

//VARIANT DIALOG ACTIONS
// export const VARIANT_OPEN_DIALOG = 'VARIANT_OPEN_DIALOG';
// export const VARIANT_CLOSE_DIALOG = 'VARIANT_CLOSE_DIALOG';

//USER ACTIONS
export const USER_REGISTER = "USER_REGISTER";
export const USER_EMAIL = "USER_EMAIL";
export const USER_LOGIN = "USER_LOGIN";